site:
 title: Bristol SU Portal Project
 url: https://bristol-su.github.io/docs
 start_page: home::index.adoc
 keys:
  google_analytics: 'UA-162373885-2'
content:
 sources:
 # Home for contents page to rest of docs site
 - url: https://github.com/bristol-su/docs
   start_path: home
   branches: [master]
 # Portal documentation
 - url: https://github.com/bristol-su/portal
   start_path: docs
   branches: [develop]
   tags: v*
 # Playground Documentation
 - url: https://github.com/bristol-su/playground
   start_path: docs
   branches: [develop]
 # SDK Documentation
 - url: https://github.com/bristol-su/support
   start_path: antora-docs
   branches: [docs/v4.x, master]
 # Control Documentation
 - url: https://github.com/bristol-su/control
   start_path: antora-docs
   branches: [develop]
 - url: https://github.com/bristol-su/control-management
   start_path: docs
   branches: [master]
 # Integrations
 - url: https://github.com/bristol-su/unioncloud-portal
   start_path: docs
   branches: [master]
 - url: https://github.com/bristol-su/airtable
   start_path: docs
   branches: [master]
 # Modules
 - url: https://github.com/bristol-su/static-page
   start_path: docs
   branches: [master]
 - url: https://github.com/bristol-su/upload-file
   start_path: docs
   branches: [master]
 - url: https://github.com/bristol-su/assign-roles
   start_path: docs
   branches: [master]
 - url: https://github.com/bristol-su/data-entry
   start_path: docs
   branches: [master]
 - url: https://github.com/bristol-su/typeform
   start_path: docs
   branches: [develop]
 - url: https://github.com/bristol-su/template
   start_path: docs
   branches: [master]
 # Services
 - url: https://github.com/bristol-su/typeform-service
   start_path: docs
   branches: [master]
 # Api Client
 - url: https://github.com/bristol-su/api-client
   start_path: docs
   branches: [develop]
 - url: https://github.com/bristol-su/api-client-toolkit
   start_path: docs
   branches: [develop]
 - url: https://github.com/bristol-su/control-api-client
   start_path: docs
   branches: [develop]
output:
 clean: true
 dir: ./docs
ui:
 bundle:
  url: https://github.com/bristol-su/docs-ui/raw/master/build/ui-bundle.zip
  #url: ./../docs-ui/build/ui-bundle.zip
  snapshot: true
 supplemental_files:
 - path: ui.yml
   contents: |
    static_files: [ .nojekyll, CNAME ]
 - path: .nojekyll
 - path: CNAME
   contents: |
    portal-docs.bristolsu.org.uk
