site:
 title: Bristol SU Portal Project
 url: bristolsu.github.io/docs
 start_page: home::index.adoc
content:
 sources:
 - url: .
   start_path: docs
 - url: https://gitlab.com/antora/demo/demo-component-a.git
 - url: https://gitlab.com/antora/demo/demo-component-b.git
   branches: [v2.0, v1.0]
   start_path: docs
ui:
 bundle:
  url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
  snapshot: true
