# This is a basic workflow to help you get started with Actions

name: Build Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */2 * * *'
  push:
    branches:
      - master
  repository_dispatch:
    types: compile_docs



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: npm install @antora/cli@2.3 @antora/site-generator-default@2.3

    # Runs a set of commands using the runners shell
    - name: Build
      run: $(npm bin)/antora --fetch antora-playbook.yml
      env:
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}

    - name: Commit new documentation
      uses: EndBug/add-and-commit@v4.3.0
      with:
        add: docs/
        author_name: Toby Twigger
        author_email: tobytwigger1@gmail.com
        message: Compile documentation
        force: true
        
    - name: HTTP Request Action
      uses: fjogeleit/http-request-action@v1.4.1
      with:
        url: http://www.google.com/ping?sitemap=https://docs.bristolsustaging.co.uk/sitemap.xml
        method: GET
        preventFailureOnNoResponse: true
